server:
  port: 8088

logging:
  level:
    org.springframework: debug
    com.jnk1124: debug

spring:
  message:
    basename: messages
  security:
    user:
      name: test
      password: passwOrd

management:
  endpoints:
    web:
      exposure:
        include: "*"